### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by Unicornelia** [rubymonsters/webapps-for-beginners#11]
**where**:
webapps-for-beginners/source/09-sinatra/03-hello_world.md

**what**:
'You should see something like this:

=>>> no image here <<<=

That was easy, wasn't it.'

**problem**:
In the middle of the text the referenced image is missing

**Comment by krivtsov** [comment]
at this [address](http://webapps-for-beginners.rubymonstas.org/sinatra/hello_world.html) the picture in place
![screenshot 2](https://user-images.githubusercontent.com/17032044/31817821-9ab91d62-b5a6-11e7-8d97-4c99265434ca.png)

**Comment by porras** [comment]
Thank you for the report, this seems to have been fixed at some point.
