### ISSUE TITLE
Missing file for the reference link in the text

### ISSUE THREAD

**Issue by Unicornelia** [rubymonsters/webapps-for-beginners#12]
**where**:
webapps-for-beginners/source/20-exercises/01-using_rubygems.md 

**what**:
By the way, if you've read the bonus chapter on _**Alternative Syntax**_ then you may have notices that we also have a perfect example of a usecase for the %(..) string syntax here

**problem**:
Link is broken, it is pointing to a non-existing page
(probably this is what is missing from the repo: 
http://ruby-for-beginners.rubymonstas.org/bonus_1/alternative-syntax.html
)

**Comment by porras** [comment]
Thank you! Fixed in #17
