### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Unicornelia** [rubymonsters/webapps-for-beginners#13]
**where**:
webapps-for-beginners/source/14-resources/03-writing_resources.md

**what**:
'However, in this course, we'll want to implement our members resource ourselves, and do all the legwork that is required.

So how about heading over to the exercise Sinatra Resource.

Give it a shot!'

**Issue**:
Link in text is pointing to this page: 
http://localhost:4567/exercises/sinatra_resource.html

**Comment by porras** [comment]
Thank you! Fixed in #15
